#! /bin/sh
#! resetear las reglas.
bspc rule -r "*"

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output VGA1 --mode 1600x900 &
feh --bg-max Pictures/bg.jpg &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a emacs -o desktop --focus '^2'
bspc rule -a otter-browser desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
